-- ==============================================================================
-- CETI Elisa Bessa Freire - Atividade Avaliativa de Matemática (9º Ano)
-- Script Oficial de Configuração do Supabase (SQL Puro sem crases)
-- ==============================================================================

-- 1. CRIAÇÃO DA TABELA DE ENVIOS
CREATE TABLE IF NOT EXISTS public.envios_atividade (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  turma VARCHAR(20) NOT NULL,
  aluno_nome VARCHAR(150) NOT NULL,
  respostas_parte1 JSONB NOT NULL,
  respostas_parte2 JSONB NOT NULL,
  fotos_urls JSONB NOT NULL,
  protocolo VARCHAR(50) NOT NULL,
  criado_em TIMESTAMPTZ DEFAULT TIMEZONE('America/Sao_Paulo', NOW()) NOT NULL,

  -- TRAVA DE ENVIO ÚNICO: Impede que o mesmo aluno envie 2 vezes na mesma turma
  CONSTRAINT aluno_turma_envio_unico UNIQUE (turma, aluno_nome)
);

-- 2. ÍNDICES DE BUSCA RÁPIDA
CREATE INDEX IF NOT EXISTS idx_envios_turma ON public.envios_atividade(turma);
CREATE INDEX IF NOT EXISTS idx_envios_aluno ON public.envios_atividade(aluno_nome);
CREATE INDEX IF NOT EXISTS idx_envios_protocolo ON public.envios_atividade(protocolo);

-- 3. SEGURANÇA ROW LEVEL SECURITY (RLS)
ALTER TABLE public.envios_atividade ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir inserção anônima de envios" ON public.envios_atividade;
DROP POLICY IF EXISTS "Permitir leitura pública de envios" ON public.envios_atividade;

-- Permite aos estudantes enviarem suas respostas
CREATE POLICY "Permitir inserção anônima de envios"
ON public.envios_atividade
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- Permite ao sistema consultar duplicidade e ao painel do professor listar os envios
CREATE POLICY "Permitir leitura pública de envios"
ON public.envios_atividade
FOR SELECT
TO anon, authenticated
USING (true);


-- 4. BUCKET DE ARMAZENAMENTO DAS FOTOS DOS CÁLCULOS
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'calculos',
    'calculos',
    true,
    10485760, -- 10MB máximo
    ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/jpg']
)
ON CONFLICT (id) DO UPDATE 
SET public = true,
    file_size_limit = 10485760;

DROP POLICY IF EXISTS "Permitir upload anônimo de cálculos" ON storage.objects;
DROP POLICY IF EXISTS "Permitir visualização pública de cálculos" ON storage.objects;

CREATE POLICY "Permitir upload anônimo de cálculos"
ON storage.objects
FOR INSERT
TO anon, authenticated
WITH CHECK (bucket_id = 'calculos');

CREATE POLICY "Permitir visualização pública de cálculos"
ON storage.objects
FOR SELECT
TO anon, authenticated
USING (bucket_id = 'calculos');


-- 5. VIEW DE CORREÇÃO AUTOMÁTICA DAS NOTAS (GABARITO OFICIAL)
-- Q1 a Q10: B
-- Q11: C | Q12: E | Q13: B | Q14: C | Q15: B | Q16: B | Q17: C | Q18: C | Q19: C | Q20: C
CREATE OR REPLACE VIEW public.vw_relatorio_notas AS
SELECT 
    id,
    protocolo,
    turma,
    aluno_nome,
    criado_em AS data_hora_envio,
    fotos_urls AS fotos_calculos,
    fotos_urls->>'q11' AS foto_q11,
    (
     -- Parte 1 (Q1 a Q10)
     CASE WHEN respostas_parte1->>'q1' = 'B' THEN 1 ELSE 0 END +
     CASE WHEN respostas_parte1->>'q2' = 'B' THEN 1 ELSE 0 END +
     CASE WHEN respostas_parte1->>'q3' = 'B' THEN 1 ELSE 0 END +
     CASE WHEN respostas_parte1->>'q4' = 'B' THEN 1 ELSE 0 END +
     CASE WHEN respostas_parte1->>'q5' = 'B' THEN 1 ELSE 0 END +
     CASE WHEN respostas_parte1->>'q6' = 'B' THEN 1 ELSE 0 END +
     CASE WHEN respostas_parte1->>'q7' = 'B' THEN 1 ELSE 0 END +
     CASE WHEN respostas_parte1->>'q8' = 'B' THEN 1 ELSE 0 END +
     CASE WHEN respostas_parte1->>'q9' = 'B' THEN 1 ELSE 0 END +
     CASE WHEN respostas_parte1->>'q10' = 'B' THEN 1 ELSE 0 END +

     -- Parte 2 (Q11 a Q20)
     CASE WHEN respostas_parte2->>'q11' = 'C' THEN 1 ELSE 0 END +
     CASE WHEN respostas_parte2->>'q12' = 'E' THEN 1 ELSE 0 END +
     CASE WHEN respostas_parte2->>'q13' = 'B' THEN 1 ELSE 0 END +
     CASE WHEN respostas_parte2->>'q14' = 'C' THEN 1 ELSE 0 END +
     CASE WHEN respostas_parte2->>'q15' = 'B' THEN 1 ELSE 0 END +
     CASE WHEN respostas_parte2->>'q16' = 'B' THEN 1 ELSE 0 END +
     CASE WHEN respostas_parte2->>'q17' = 'C' THEN 1 ELSE 0 END +
     CASE WHEN respostas_parte2->>'q18' = 'C' THEN 1 ELSE 0 END +
     CASE WHEN respostas_parte2->>'q19' = 'C' THEN 1 ELSE 0 END +
     CASE WHEN respostas_parte2->>'q20' = 'C' THEN 1 ELSE 0 END
    ) AS acertos,

    ROUND(
        (
            (
             CASE WHEN respostas_parte1->>'q1' = 'B' THEN 1 ELSE 0 END +
             CASE WHEN respostas_parte1->>'q2' = 'B' THEN 1 ELSE 0 END +
             CASE WHEN respostas_parte1->>'q3' = 'B' THEN 1 ELSE 0 END +
             CASE WHEN respostas_parte1->>'q4' = 'B' THEN 1 ELSE 0 END +
             CASE WHEN respostas_parte1->>'q5' = 'B' THEN 1 ELSE 0 END +
             CASE WHEN respostas_parte1->>'q6' = 'B' THEN 1 ELSE 0 END +
             CASE WHEN respostas_parte1->>'q7' = 'B' THEN 1 ELSE 0 END +
             CASE WHEN respostas_parte1->>'q8' = 'B' THEN 1 ELSE 0 END +
             CASE WHEN respostas_parte1->>'q9' = 'B' THEN 1 ELSE 0 END +
             CASE WHEN respostas_parte1->>'q10' = 'B' THEN 1 ELSE 0 END +
             CASE WHEN respostas_parte2->>'q11' = 'C' THEN 1 ELSE 0 END +
             CASE WHEN respostas_parte2->>'q12' = 'E' THEN 1 ELSE 0 END +
             CASE WHEN respostas_parte2->>'q13' = 'B' THEN 1 ELSE 0 END +
             CASE WHEN respostas_parte2->>'q14' = 'C' THEN 1 ELSE 0 END +
             CASE WHEN respostas_parte2->>'q15' = 'B' THEN 1 ELSE 0 END +
             CASE WHEN respostas_parte2->>'q16' = 'B' THEN 1 ELSE 0 END +
             CASE WHEN respostas_parte2->>'q17' = 'C' THEN 1 ELSE 0 END +
             CASE WHEN respostas_parte2->>'q18' = 'C' THEN 1 ELSE 0 END +
             CASE WHEN respostas_parte2->>'q19' = 'C' THEN 1 ELSE 0 END +
             CASE WHEN respostas_parte2->>'q20' = 'C' THEN 1 ELSE 0 END
            )::numeric / 20.0 * 10.0
        ), 1
    ) AS nota_final

FROM public.envios_atividade
ORDER BY turma ASC, aluno_nome ASC;
